### ISSUE TITLE
Results: Missing Feature: 2D histogram in PDF and all except last Results GUI with roi manager, the regression line is absent

### ISSUE THREAD

**Issue by chalkie666** [fiji/Colocalisation_Analysis#14]
the regression line (from autothresholds) is drawn on the 2D histogram in SingleWindowDisplay, but not from the PDFWriter. 
It is missing in the SingleWindowDisplay ResultsHandler GUIs for all but the GUI for the last ROI in the list  in the ROI manager.

**Comment by etarena** [comment]
@chalkie666  - what do you mean by 'except last results GUI with roi manager' ???  what is this exception exactly?

**Comment by etarena** [comment]
nope @chalkie666 - i got it.  you mean if you have multiple rois selected... the regression line is only printed in the GUI for the final roi.  right?
