### ISSUE TITLE
Results: change 1st line of results, result from -1 to Done or Complete

### ISSUE THREAD

**Issue by chalkie666** [fiji/Colocalisation_Analysis#23]
@tomka added ability to have string resilts , so can now have a string result here: instead of 
Colocalization_of_colocsample1b-green.tif_versus_colocsample1b-red.tif_1827000661
-1

to 

Colocalization_of_colocsample1b-green.tif_versus_colocsample1b-red.tif_1827000661 Done
or
Colocalization_of_colocsample1b-green.tif_versus_colocsample1b-red.tif_1827000661 Complete
or 
Colocalization_of_colocsample1b-green.tif_versus_colocsample1b-red.tif_1827000661 Finished Computing results.

**Comment by tomka** [comment]
Wouldn't it be more descriptive to just have a string field called "Job name" which then holds the the name? E.g.:

Name|Result
-------|---------
Job name|Colocalization_of_colocsample1b-green.tif_versus_colocsample1b-red.tif_1827000661|

**Comment by chalkie666** [comment]
Yes. Actually it would.
I can do it next week...

D

**Comment by chalkie666** [comment]
@tomka fixed in commit ca6cb3e 
doesnt need code review, its a tiny change, i tested , it works as expected. 
So I will merge it into master already
