### ISSUE TITLE
Results: results appear in different order in SingleWindowDisplay output and log window

### ISSUE THREAD

**Issue by chalkie666** [fiji/Colocalisation_Analysis#25]
eg  the result text 
threshold regression bisection
appears first (log) or in the middle (PDF and SingleWindowDisplay) in the order of results.... 
order should be the same in every results output case. 

(Also warnings in the PDF output appear in the middle, instead of the top of the list... See #53)

**Comment by etarena** [comment]
It seems that in the log window... 3 extra, redundant lines are printed at the beginning as compared to the results window, which include:

1. Coloc_Job_Name
2. Mask Type Used
3. Threshold regression

Otherwise, the order along with the results & log windows are the same.  And the only difference between these and the PDF appears to be the warnings being inserted between 'Mask ID Used' and 'm (slope)'.  Is this correct @chalkie666 ?

**Comment by chalkie666** [comment]
@etarena yes we should stop the redundant lines from being output into the log. I expect that was my fault. It's something to do with some part of the code being run twice for some reason I could not figure out.

**Comment by etarena** [comment]
@chalkie666  ok.  i'll work on this one next... but might split it out from the PDF warning issue.  I might file that one separately and work on this piecewise.  is that ok?

**Comment by chalkie666** [comment]
Sure!

**Comment by etarena** [comment]
@chalkie666 - it seems this exception of 3 extra, redundant lines all call the handleValue(String name, String value) method...  so perhaps they are getting added twice to 'valueResults' List ??

**Comment by chalkie666** [comment]
@etarena yes it might be that. I remember trying to find where things were being done twice but didn't find it. The complexity of the Plugin design doesn't help here. Johannes suggested to rip out some or all of the results handler and data container complexity and use builtin imagej gadgets...  And I agree. For the reasons you now face.

**Comment by etarena** [comment]
@chalkie666 good news... i found where in the code these extra lines are being printed to the log window... in Coloc_2 class... lines 490-494: constitutes a loop that 'let the algorithms feed their results to the handler' ... so - we have progress!

**Comment by chalkie666** [comment]
@etarena  Good catch!

**Comment by etarena** [comment]
@chalkie666 - I think I found it... but am not sure how best to fix it.  It seems to be in the PDFWriter class... line 118.  there is code there to "send (output parameter name, value)  to IJ.log for scraping batch results".  If I comment out this line of code `IJ.log(name + ", " + value);` - the extra log printing is no longer an issue and 'solves' the problem without any apparent, adverse effects... just let me know your thoughts on this when you are able.

**Comment by chalkie666** [comment]
@etarena ok, that was my fault then....   

 i added those IJ.log lines allover the place. if you see it prevents the duplication, but the results are still printed correctly to ij log, then all good!      ;-)
