### ISSUE TITLE
Scatterplot green vs red pixel intensity - possible generic color scheme?

### ISSUE THREAD

**Issue by etarena** [fiji/Colocalisation_Analysis#36]
Was [a user question from the mailing list](https://list.nih.gov/cgi-bin/wa.exe?A2=IMAGEJ;858e2fb4.1508):
> I recently used the Coloc2 pluging for Fiji and it generated a scatterplot of green vs red pixel intenstiy.
>
> I was wondering if there is anyway in getting the generic colour scheme relating to intensity as a key for a figure?

**Comment by chalkie666** [comment]
@etarena 
It uses the ImageJ fire lookup table, with log or not log scaling according to the log checkbox

You can get the actual numbers 🔢 by clicking list.

**Comment by chalkie666** [comment]
I didn't get the original email yet as I get the digest mode of the mailing list.   But I will answer it as above. And I will point it out in the docs and send a link to that

So can close this issue

**Comment by etarena** [comment]
thanks dan @chalkie666 .  i can send the email... no worries.

**Comment by chalkie666** [comment]
Section 8.2.1 of how to use Coloc 2 section of wiki page.

**Comment by etarena** [comment]
i see it clearly stated now in the wiki.  sorry to bother!  and thanks again... i'm still in the beginning.

**Comment by chalkie666** [comment]
I just added it s minute or two ago!

**Comment by etarena** [comment]
oh!  that's why i missed it!  ha!
