### ISSUE TITLE
Ops: liICQ

### ISSUE THREAD

**Issue by etarena** [fiji/Colocalisation_Analysis#54]
Move Li ICQ into Ops Framework... 

see issue #12

**Comment by etarena** [comment]
Implemented in imagej-ops on `coloc` branch as `LiICQ`.

**Comment by lacan** [comment]
Hi @etarena, 
I wanted to see what the LiICQ looked like in ops, but I cannot find the coloc branch?
Best

**Comment by ctrueden** [comment]
@lacan See [here](https://github.com/imagej/imagej-ops/compare/coloc).
