### ISSUE TITLE
Access Log Window Statistics Output by API

### ISSUE THREAD

**Issue by stephanmg** [fiji/Colocalisation_Analysis#62]
As discussed with @ctrueden I'm opening this issue,
thanks for looking into this.

**Synopsis:**
It would be useful to be able to access all the statistics outputted in the Log Window of ImageJ
by some API functions from Coloc2, then one does not need to try to parse/decipher the Log Window output manually.

It is currently developed on the branch:
`https://github.com/fiji/Colocalisation_Analysis/compare/results-api`

**Comment by etarena** [comment]
This issue was resolved in [this merge](https://github.com/fiji/Colocalisation_Analysis/commit/d9f3613f194e13b010c19b176fd00e8176b453a5).
