### ISSUE TITLE
Pearson's correlation from ImageJ2 macro

### ISSUE THREAD

**Issue by christianrickert** [fiji/Colocalisation_Analysis#72]
Is there a way to access the Pearson's correlation calculation from an ImageJ2 macro (macro language)?

The plugin is properly installed and is available to ImageJ2:

![QuickSearch](https://user-images.githubusercontent.com/19319377/103239553-16262a80-490b-11eb-9c00-287fc4f3b966.PNG)

I've tried to call the Pearson' correlation function directly:
```
// prepare two images to correlate
run("Blobs (25K)");
rename("blobs");

run("Blobs (25K)");
rename("nobs");
run("Add Noise");

// calculate Pearson's correlation
result = call("net.imagej.ops.coloc.pearsons.DefaultPearsons", "blobs", "nobs");
```
But I get an error message:

![error](https://user-images.githubusercontent.com/19319377/103239588-381fad00-490b-11eb-8ad7-d764a0247956.PNG)

Any ideas?

**Comment by ctrueden** [comment]
@christianrickert You can do it by calling the `coloc.pearsons` op as follows:
```groovy
#@ Dataset d1
#@ Dataset d2
#@ OpService ops
coeff = ops.coloc().pearsons(d1, d2)
println(coeff)
```
Note that this is a Groovy script, not an ImageJ1 macro. You cannot call ops easily from the IJ1 macro language.
